### ISSUE TITLE
Training fails to converge

### ISSUE THREAD

**Issue by xiaohuyz** [neurosim/MLP_NeuroSim_V3.0#10]
I use the dafault data but only change the cores used. However, the Training floats at 60%. And when i only change the algorithm to Adam, it even get worse. the training stays at 12% and cannot improve.

**Comment by neurosim** [comment]
For Adam, you might need to reduce the learning rate to like 0.1, 0.05. The default data (a-Ag RRAM) has pretty bad non-linearity, it might not converge very well.

**Comment by xiaohuyz** [comment]
thanks. I see.



At 2022-03-26 04:40:58, "NeuroSim" ***@***.***> wrote:

For Adam, you might need to reduce the learning rate to like 0.1, 0.05. The default data (a-Ag RRAM) has pretty bad non-linearity, it might not converge very well.
