### ISSUE TITLE
About the choice of ReRAM device type

### ISSUE THREAD

**Issue by leibo-hust** [neurosim/MLP_NeuroSim_V3.0#6]
Hello, when I was reading the **user manual** you gave, I found that ReRAM has many different types of devices, such as **Ag:a-Si** and **TaOx/HfOx**. Why in your simulator, the **RealDevice** type uses **Ag:a-Si** instead of **TaOx/HfOx**?  It seems that **TaOx/HfOx** has lower write latency and higher accuracy. Is it because of other limitations? How should I choose when I select the device type? thank you very much!

**Comment by leibo-hust** [comment]
If I want to change the device type to **TaOx/HfOx**, what parameters and corresponding parameter values of RealDevice in **cell.cpp** should I change? Thank you

**Comment by neurosim** [comment]
Hi, you need to change the maxConductance/minConductance, writeVoltageLTP/LTD, writePulseWidthLTP/LTD, maxNumLevelLTP/LTD, NL_LTP/LTD, sigmaDtoD et.al. There is a tutorial in the user manual under the folder "documens". Thank you.

**Comment by leibo-hust** [comment]
Thanks, I saw the **user_manual.pdf**, but I don't know how to correspond the data in the table with these variables. For example, which row in Table 2 corresponds to **maxConductance/minConductance**.
