### ISSUE TITLE
May I change the training MNIST dataset to CIFAR_10 dataset, if so how can?

### ISSUE THREAD

**Issue by zhangysjlu** [neurosim/MLP_NeuroSim_V3.0#7]
Hi, I would like to run CIFAR-10 dataset on your simulator, But the manual said the input neuron number is fixed to 400, how could I change it. Thanks?

**Comment by neurosim** [comment]
You can change the input neuron number to be 32*32*3 for CIFAR-10 images in param.cpp. You need to unroll the input image to 32*32*3. However, the performance of this simple 2-layer MLP network may not be very good for CIFAR-10.

**Comment by zhangysjlu** [comment]
I would like to implement CNN simulation based on your simulator. May I know if it is possible to do so? The circuit block is free to change? Looking forward to your reply. Thank you very much!
