### ISSUE TITLE
Excessive maximum conductivity, 9.8% problem

### ISSUE THREAD

**Issue by taehyeonkim123** [neurosim/MLP_NeuroSim_V3.0#9]
Hello, your program is very useful. Thank you very much. I have some issue. 
Changing the maximum conductivity value in the parameter settings in Cell.cpp from the example (5e-6) to 1.0e-3 yields a consistent extraction of 9.80%. 
The rest of the parameter values remained the same. Does increasing the max conductance/min conductance values cause problems? 
Or is there a parameter that needs to be modified together when the maximum conductance becomes excessively large? 
Thank you.

**Comment by hjteixeira** [comment]
This issue still affects me. My group works with devices that have _max conductance_ values in the order of **1e-3**, and even with good linearity, DR>4 and #G>=64 it still gets stuck at **9.8%** convergence @neurosim
